services:
    security.authentication.success_handler:
        class:  AG\Bundle\UserBundle\Security\AuthenticationSuccessHandler
        arguments:  ["@security.http_utils", {}, "@session", "@router"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    security.authentication.failure_handler:
        class:  AG\Bundle\UserBundle\Security\AuthenticationFailureHandler
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger", "@translator"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    ag.user_provider.username_email:
        class:  AG\Bundle\UserBundle\Security\EmailUserProvider
        public: false
        arguments:  ["@fos_user.user_manager"]
        
    ag.user.ulogin:
        class:  AG\Bundle\UserBundle\Lib\Ulogin
        arguments:  ["@service_container"]
        
    ag.user.payy:
        class:  AG\Bundle\UserBundle\Lib\Payy
        arguments:  ["@service_container"]
