services:
    security.authentication.success_handler:
        class:  AG\Bundle\UserBundle\Security\AuthenticationSuccessHandler
        arguments:  ["@security.http_utils", {}]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    security.authentication.failure_handler:
        class:  AG\Bundle\UserBundle\Security\AuthenticationFailureHandler
        arguments:  ["@http_kernel", "@security.http_utils", {}, "@logger"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
