imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    max.sms.interval: 10

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: [127.0.0.1]
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fos_csrf_provider: "@form.csrf_provider"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
        uglifycss:
            bin: /usr/local/bin/uglifycss
            node: /usr/bin/nodejs
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
            node: /usr/bin/nodejs
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/local/lib/node_modules/]
            apply_to: "\.less$"

# Swiftmailer Configuration
swiftmailer:
    auth_mode:  login
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    default_locale: ru_RU
    mongodb:
        default:
            blameable:      true
            timestampable:  true
            loggable:       true
            softdeleteable: true
            sluggable:      false
            translatable:   false
            uploadable:     false
            tree:           false
            sortable:       false

# FOSUserBundle Configuration
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: AG\Bundle\UserBundle\Document\User

# OrnicarGravatarBundle Configuration
ornicar_gravatar:
    rating: x
    size: 50
    default: mm

# FOSJsRoutingBundle Configuration
fos_js_routing:
    routes_to_expose: [fos_user_security_check, fos_user_security_login]

# DoctrineMongoDBBundle Configuration
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_url%
            options: {}
    default_database: %mongodb_database%
    document_managers:
        default:
            connection: 'default'
            auto_mapping: true
            filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\ODM\SoftDeleteableFilter
                        enabled: true
            mappings:
                gedmo_loggable:
                    type: annotation
                    prefix: Gedmo\Loggable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
                    alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                    is_bundle: false
#                gedmo_translatable:
#                    type: annotation
#                    prefix: Gedmo\Translatable\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document"
#                    alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
#                    is_bundle: false
#                gedmo_translator:
#                    type: annotation
#                    prefix: Gedmo\Translator\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Document"
#                    alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
#                    is_bundle: false
#                gedmo_tree:
#                    type: annotation
#                    prefix: Gedmo\Tree\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"
#                    alias: GedmoTree # this one is optional and will default to the name set for the mapping
#                    is_bundle: false