home:
    path:      /
    defaults:  { _controller: AGCarBundle:Search:index }

ag_car:
    resource: "@AGCarBundle/Controller/"
    type:     annotation
    prefix:   /
    
ag_user:
    resource: "@AGUserBundle/Controller/"
    type:     annotation
    prefix:   /user

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

